### ISSUE TITLE
Menampilkan Data Dosen (Bagian I)

### ISSUE THREAD

**Issue by fitriadewi09** [fitriadewi09/proyek-web-19108001-2020#1]
1) Buatlah kode program menggunakan CI (CodeIgniter) untuk menampilkan data dosen
2) Setelah itu, Push ke dalam Branch Dosen
3) Adapun file yang harus dipush ke dalam branch antara lain : 
    - file model (m_dosen.php), 
    - view (v_dosen.php),
    - dan controller (data_dosen.php).

**Comment by wdysr** [comment]
Terima kasih sudah menyelesaikan source code-nya. Source code telah diperiksa, dan menurut saya sudah benar untuk pembuatan data dosen menggunakan Codeigniter. Code yang dipush ke dalam repositori juga lengkap dan tidak ada kekurangan. Source code yang digunakan juga mudah dipahami sesuai dengan beberapa tugas kemarin sehingga saya tidak merasa asing dengan code tersebut. Dari pandangan pribadi, Fitria Dewi mendapat nilai **95** karena tampilan yang diberikan juga rapih karena menggunakan bootstrap. Terima kasih.

**Comment by fitriadewi09** [comment]
Baik, terima kasih banyak atas comment serta penilaian yang telah Anda berikan untuk proyek ini.

**Comment by yaddarabullah** [comment]
Oke, sudah saya terima invitation nya
